image:
  file: .gitpod.Dockerfile
checkoutLocation: '.'
tasks:
  - name: Clean root and grab useful exercises.
    before: |
      rm -rfv ./exercise* ./.git ./content
      sudo mv /home/gitpod/linux-exercises/* .
      clear
